### ISSUE TITLE
Image not showing.

### ISSUE THREAD

**Issue by sc0ttwood** [gkasdorf/memmy#261] opened 2023-06-30 19:22 UTC
I was scrolling along when suddenly I realised that my post image was not showing, refreshed the page, restarted that app yet it still has not changed

App:
![IMG_1622](https://github.com/gkasdorf/memmy/assets/138073160/3f7cc488-41db-4562-985d-3af9e0dbf6bb)

Website:
![IMG_1623](https://github.com/gkasdorf/memmy/assets/138073160/5ebd092c-801c-42a6-8cd3-692d63f6ac7f)

Link:
https://lemmy.world/post/863028

**Comment by sgriff96** [comment] 2023-06-30 21:30
Duplicate of #223

**Closed** 2023-06-30 21:30 UTC
Labels: bug, linear
