### ISSUE TITLE
[BUG] Some videos keep playing audio after closing web browser

### ISSUE THREAD

**Issue by JeremyLeland** [gkasdorf/memmy#137] opened 2023-06-24 19:21 UTC
**Describe the bug**
Some videos playing in the internal web browser do not stop after closing the browser (the audio is still playing). I've noticed this with Twitter videos so far.

**To Reproduce**
1. Go to a comment with a link to a twitter video, such as https://lemmy.world/comment/486102
3. Tap the link (e.g. https://twitter.com/NOELreports/status/1672359292089913348?t=EmZwYu-W1PgheL3emA9WTw&s=19 )
4. Start playing the video
5. Tap "Close" in upper left corner

**Expected behavior**
The video should stop playing (as you can no longer see it).

**Actual behavior**
The video is still playing in the background (you can still hear the audio).

**Smartphone (please complete the following information):**
 - Device: iPhone SE
 - OS: 16.5
 - Version 0.0.1 (61)

**Additional context**
Once you are in this state, the only way to stop the audio is to tap another link (as long as it will open in the web browser).

**Comment by JeremyLeland** [comment] 2023-06-24 19:31
I just realized that you can also control the audio from the iOS lock screen, so you aren't as stuck as I thought.

I could see someone intentionally doing this to play a song on youtube and then go back to scrolling Lemmy. I personally found it counterintuitive -- I expected everything to stop when I went back to the Lemmy post.

**Comment by gkasdorf** [comment] 2023-06-25 00:55
What website was this on? I've tried to reproduce in a simulator and on my phone and wasn't able to. Did this happen multiple times? It's possible this was some sort of iOS bug.

**Comment by JeremyLeland** [comment] 2023-06-25 02:35
Here is a video of me reproducing the issue with the post linked above:

https://github.com/gkasdorf/memmy/assets/50390633/ddf60f37-9eba-4f31-ab2a-7d6e8e0585da

It reproduces consistently with videos on twitter like the one above. I can link other examples of pages with video that do this if it helps.

**Comment by gkasdorf** [comment] 2023-06-25 02:37
Let me test with a Twitter link and I'll get back. If it's an issue on my end I'll see what I can do 👍

**Comment by JeremyLeland** [comment] 2023-06-25 02:51
This does not repro with YouTube videos. I also don't see an entry in the lock screen to control YouTube videos -- they must do something different (perhaps to prevent people from playing music in the background without paying for premium?).

Here's another video that repros:
* https://lemmy.world/post/510567: https://yewtu.be/watch?v=42D-upSioWE

(I'm having trouble finding other posts with non-youtube videos, I'll keep looking)

**Comment by gkasdorf** [comment] 2023-06-25 02:52
Ok cool, that might be why I couldn't repro. I'll test this in a bit and see. I might need to do something extra to actually terminate the browser. I'll update you shortly.

**Comment by gkasdorf** [comment] 2023-06-25 04:59
Looks like it was an open issue here. https://github.com/expo/expo/issues/22406

Let me see if these updates ever got merged and if so I will try and update the module. Cheers.

**Comment by gkasdorf** [comment] 2023-06-25 05:21
Fixed here. https://github.com/gkasdorf/memmy/commit/82af9b4928a72bb804ce236346686b38f70ef6f0 Thanks for the report! I'll push it in the next update.

**Closed by gkasdorf** 2023-06-25 05:21 UTC
Labels: bug, invalid
